ToDoList/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls"), name="core"),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path

from core.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    mark_as_done,
    mark_as_undo,
    TagListView,
    TagUpdateView,
    TagDeleteView,
    TagCreateView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/",
         TaskCreateView.as_view(),
         name="task-create"),
    path("tasks/<int:pk>/edit/",
         TaskUpdateView.as_view(),
         name="task-edit"),
    path("tasks/<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"),
    path("tasks/<int:pk>/mark-as-done/",
         mark_as_done,
         name="task-done"),
    path("task/<int:pk>/mark-as-undo/",
         mark_as_undo,
         name="task-undo"),
    path("tags/",
         TagListView.as_view(),
         name="tag-list"),
    path("tags/create/",
         TagCreateView.as_view(),
         name="tag-create"),
    path("tags/<int:pk>/edit/",
         TagUpdateView.as_view(),
         name="tag-edit"),
    path("tags/<int:pk>/delete/",
         TagDeleteView.as_view(),
         name="tag-delete"),
]

app_name = "core"

core/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63, unique=True)

    class Meta:
        verbose_name_plural = "Tags"
        verbose_name = "Tag"

    def __str__(self):
        return self.name


class Task(models.Model):
    task_name = models.CharField(
        max_length=255,
    )
    description = models.TextField()
    deadline = models.DateField(null=True, blank=True)
    done = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)
    tag = models.ManyToManyField(Tag, related_name="tasks", blank=True)

    def __str__(self):
        return self.task_name

    def is_done(self) -> str:
        return "Done" if self.done else "Not done"

core/views.py
from django.http import (HttpRequest,
                         HttpResponse,
                         HttpResponseRedirect)
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from core.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "core/index.html"
    ordering = ["done", "created_at"]


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("core:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("core:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("core:task-list")


class TagListView(generic.ListView):
    model = Tag
    ordering = ["name"]


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("core:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("core:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("core:tag-list")


def mark_as_done(request: HttpRequest, pk: int) -> HttpResponse:
    task = get_object_or_404(Task, id=pk)
    task.done = True
    task.save()
    return HttpResponseRedirect(
        request.META.get("HTTP_REFERER",
                         reverse_lazy(viewname="core:task-list"))
    )


def mark_as_undo(request: HttpRequest, pk: int) -> HttpResponse:
    task = get_object_or_404(Task, id=pk)
    task.done = False
    task.save()
    return HttpResponseRedirect(
        request.META.get("HTTP_REFERER",
                         reverse_lazy(viewname="core:task-list"))
    )

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Task Manager</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>

<body>
<div>
  <div>
    <div>

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    

    </div>
  
      <div class="main">
        {% block content %}
        {% endblock %}
      
        {% block pagination %}
          {% include "includes/pagination.html" %}
        {% endblock %}
      </div>
      
  </div>
</div>
</body>

</html>

templates/core/index.html
{% extends "base.html" %}

{% block content %}
<div>
  <h1 style="text-align: center">To do App
    <a class="add-button" href="{% url "core:task-create" %}">(add new task)</a>
  </h1>
  <div>
  {% for task in task_list %}
    <h3>{{ task.task_name }} 
      {% if task.done %} 
      <a class="btn btn-secondary" href="{% url "core:task-undo" pk=task.id %}">Undo</a>
      {% else %}
      <a class="btn btn-success" href="{% url "core:task-done" pk=task.id %}">Complete</a>
      {% endif %}
    </h3>
    {% if task.done %}
    <p> 
      <span style="color: green">{{ task.is_done }}</span>
    </p>  
    {% else %}  
    <p>
      <span style="color: red">{{ task.is_done }}</span>
    </p>  
    {% endif %}

    <p>{{ task.description }}</p>
    <span>Created: {{ task.created_at }}</span>
    {% if task.deadline %}
    <span>Deadline: {{ task.deadline }}</span>
    {% endif %}
    <p>Tags: {% for tag in task.tag.all %} {{ tag }}, {% endfor %}</p>
    <span><a href="{% url "core:task-edit" pk=task.id %}">Update</a> |
    <a href="{% url "core:task-delete" pk=task.id %}">Delete</a>
    </span>
    <hr>
    </div>
  {% endfor %}
</div>
{% endblock %}

templates/core/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/core/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update tag, Create tag" }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/core/tag_list.html
{% extends "base.html" %}

{% block content %}
<div>
  <h2 style="text-align: center; font-weight: bold">Tag list
    <a class="add-button" href="{% url "core:tag-create" %}">(add new tag)</a>
  </h2>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tag_list %}
    <tr>
      <td>{{ tag.name }}</td>
      <td><a href="{% url "core:tag-edit" pk=tag.id %}">Update</a></td>
      <td><a href="{% url "core:tag-delete" pk=tag.id %}">Delete</a></td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

templates/core/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/core/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update task, Create task" }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'core:task-list' %}">Home page</a></li>
  <li class="list-group-item"><a href="{% url 'core:tag-list' %}">Tags</a></li>
</ul>